name: Nightly Fuzz Testing

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  fuzz:
    name: Extended Fuzz Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run extensive proptest fuzzing
        run: |
          cd crates/ferra_lexer
          # Run proptest with significantly more cases nightly
          PROPTEST_CASES=100000 cargo test fuzz --release -- --nocapture
        env:
          RUST_BACKTRACE: full

      - name: Report results
        run: echo "✅ Extended proptest fuzzing (100k cases) completed successfully" 